apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: hotel-website-push-
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
spec:
  pipelineSpec:
    tasks:
      - name: test-trigger
        taskSpec:
          steps:
            - name: echo
              image: registry.access.redhat.com/ubi9/ubi-minimal
              script: |
                #!/usr/bin/env sh
                echo "Hotel website pipeline triggered"
